# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-11 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baiyue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='md_link',
            table='Md_link',
        ),
    ]
